trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  SCAN_EXIT_CODE: 0

steps:
- script: |
    echo "Downloading Aqua ScannerCLI executable binary..."
    wget -O scannercli https://download.aquasec.com/scanner/2022.4/scannercli --user=$(Aqua_User) --password=$(Aqua_PW)
    chmod +x scannercli
    echo "Aqua ScannerCLI downloaded and permissions set."
  displayName: 'Download Aqua ScannerCLI'

- script: |
    echo "Scanning the image..."
    ./scannercli scan -H $(Aqua_Environment_URL) -U $(Env_User) -P $(Env_PW) --code-scan $(Build.SourcesDirectory) --htmlfile $(Build.SourcesDirectory)/AquaSecurity.html --jsonfile $(Build.SourcesDirectory)/AquaSecurity.json
    exitCode=$?
    echo "Scan command exit code: $exitCode"
    echo "##vso[task.setvariable variable=SCAN_EXIT_CODE]$exitCode"
    echo "Scan completed."
    exit $exitCode
  displayName: 'Scan Image with Aqua ScannerCLI'
  continueOnError: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'AquaSecurityResults'
    publishLocation: 'Container'
  condition: succeededOrFailed()
  displayName: 'Publish Security Scan Reports'

- script: |
    if [ $(SCAN_EXIT_CODE) -ne 0]; then
      echo "Aqua Scan failed with vulnerabilities."
      exit $(SCAN_EXIT_CODE)
  displayName: 'Fail Build If Aqua Scan Failed'