trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Downloading Aqua ScannerCLI executable binary..."
    wget -O scannercli https://download.aquasec.com/scanner/2022.4/scannercli --user=$(Aqua_User) --password=$(Aqua_PW)
    chmod +x scannercli
    echo "Aqua ScannerCLI downloaded and permissions set."
  displayName: 'Download Aqua ScannerCLI'

- script: |
    echo "Scanning the image..."
    ./scannercli scan --dockerless -H $(Aqua_Environment_URL) -U $(Aqua_User) -P $(Aqua_PW) --local $(Vulnerable_Image) --htmlfile AquaSecurity.html --jsonfile AquaSecurity.json
    echo "Scan completed."
  displayName: 'Scan Image with Aqua ScannerCLI'
  continueOnError: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'AquaSecurityResults'
    publishLocation: 'Container'
  displayName: 'Publish Security Scan Reports'
