pipeline {
    agent any
    tools {
        nodejs "Node"
        maven "Maven"
        snyk "SnykLatest"
    }
    environment{
        MOBB_API_KEY = credentials('mobb-api-key')
    }
    stages {
        stage('Build') {
                steps {
                    //sh 'mvn -B -DskipTests clean package'
                    //withDockerRegistry([credentialsId: "dockerhublogin", url: ""]){
                   //     script {
                   //        app = docker.build("idanohh/myjenkins")
                  //      }
                //   }
                    echo "Building...Done"
                }
            }
        
        stage('Run Snyk Container Scan') {
            steps {
                    snykSecurity(
                        snykInstallation: 'snyk@latest',
                        snykTokenId: 'organisation-snyk-token',
                        failOnIssues: false,
                        additionalArguments: '--container idanohh/myjenkins'
                        )
                    }
        }
             
        stage('Run Container Scan') {
            steps {
                    snykSecurity(
                        snykInstallation: 'snyk@latest',
                        snykTokenId: 'snyk-api-key',
                        failOnIssues: false,
                        additionalArguments: '-all-projects -d'
                        )
                
                withCredentials([string(credentialsId: 'SNYK_TOKEN',variable:'SNYK_TOKEN')]){
                    script{
                        try{
                            sh 'snyk container test idanohh/myjenkins'
                        }
                        catch (err){
                            echo err.getMessage()
                        }
                    }
                }
            }
        } 
        stage('Test') {
            steps {
                //sh 'mvn test'
                echo "Testing...Running"
            }
            post {
                always {
                    // junit 'target/surefire-reports/*.xml'
                    echo "Testing...Done"

                }
            }
        }
   
        stage('Run Mobb on the findings and get fixes') {
            steps {
                sh 'npx mobbdev scan --repo https://github.com/idanshimon/mobb-simple-java-example --scanner snyk --ref master --ci --api-key ${MOBB_API_KEY}'
            }
        }    
        stage('Deliver') {
            steps {
                // sh './jenkins/scripts/deliver.sh'
                echo "Delivering...Done"
            }
        }
    }
}
