pipeline {
    agent any
    tools{
        maven "Default-Maven"
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete'){
            steps{
                echo 'Job Complete!'
                sh apt update
                sh apt install nodejs npm
                sh npx mobbdev scan --repo https://github.com/mobb-demo/mobb-simple-java-example.git --scanner snyk --ref master
            }
        }
    }
}
