pipeline {
    agent any
    tools {
        nodejs "Node"
    }
    stages {

        stage('Setup Node') {
            steps {
                // Mimic the behavior of actions/setup-node@v3.6.0
                
                // curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
                // apt-get install -y nodejs
                // node --version
                sh '''
                node --version
                npm --version
                '''
            }
              
        }
        stage('Run Mobb on the findings and get fixes') {
            steps{
                sh '''
                npx mobbdev scan --repo https://github.com/mobb-demo/mobb-simple-java-example --scanner snyk --ref master
                '''
            }
        }
    }
}
